name: deploy

on:
  push:
    branches: [ deploy ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: deploy
    steps:
      - uses: actions/checkout@v3
      - name: Hello
        run: echo ${{ secrets.SECRET_TEST }}
      - run: ./gradlew assembleDebug